/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public String getGreeting() {
		return "Hello World";        
	}

public static void main(String[] args) {

/*
	In my video, I recommended that a static method be created to call into the launch method.
	I did this because of the following error that I got as a result of calling launch directly from
	main. I did not realize at the time that there is an overloaded method of launch that takes a reference
	to the class that extends from Application. Now, why the launch method cannot infer that from the 
	class one is calling it from, I am not sure (I have not looked at the JavaFX code), but the code below works.

	Exception in thread "main" java.lang.RuntimeException: Error: class App is not a subclass of javafx.application.Application
					at javafx.application.Application.launch(Application.java:298)
					at App.main(App.java:10)
*/

//        HelloWorld.runme(args);

        HelloWorld.launch(HelloWorld.class, args);
    }
}
